#!/usr/bin/env python3
"""Build this package's data at release time (QG Reference): check, derive, generate.

    python scripts/build.py           check, then write derived/ and load.sql
    python scripts/build.py --check   check only; fail if derived/ or load.sql are stale

1. published/ (at the repo root, fetched by scripts/fetch_published.py; never committed or
   shipped): every file present matches the SHA-256 in SOURCE.json.
2. facts/: valid against the shared JSON Schema (data/owner-list.schema.json).
3. derived/ and load.sql: regenerated from facts/ and SOURCE.json.

Build tooling only (planning/QSO-GRAPH-REFERENCE-DATA.md decision 6): users never run it.
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

import jsonschema

ROOT = Path(__file__).resolve().parent.parent
PKG = next(p for p in (ROOT / "src").iterdir() if (p / "data" / "SOURCE.json").exists())
DATA = PKG / "data"
PUBLISHED = ROOT / "published"  # the owner's files: fetched, checked, never shipped
sys.path.insert(0, str(Path(__file__).resolve().parent))
import package_build  # noqa: E402  (this package's own readers and derived files)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def dump(obj) -> str:
    return json.dumps(obj, indent=2, ensure_ascii=False) + "\n"


def check_published(source: dict) -> None:
    for name, meta in source["published"].items():
        path = PUBLISHED / name
        if not path.exists():
            print(f"note: published/{name} not fetched (scripts/fetch_published.py); not checked")
            continue
        got = sha256(path)
        if got != meta["sha256"]:
            sys.exit(f"published/{name}: SHA-256 {got} does not match SOURCE.json {meta['sha256']}")


def check_facts(source: dict) -> dict[str, dict]:
    schema = json.loads((DATA / "owner-list.schema.json").read_text(encoding="utf-8"))
    facts = {}
    for name in source["facts"]:
        d = json.loads((DATA / "facts" / name).read_text(encoding="utf-8"))
        jsonschema.validate(d, schema)
        facts[name] = d
    return facts


def sql_str(v) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if isinstance(v, int):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def load_sql(source: dict, facts: dict[str, dict]) -> str:
    s = source["schema"]
    adif = source["adif_version"]
    out = [
        "-- " + "=" * 77,
        f"-- {s}: {source['title']} (QG Reference)",
        "-- GENERATED by scripts/build.py from data/facts and data/SOURCE.json. Do not edit by hand.",
        f"-- Owner: {source['owner']}. Document: {source['document']}, edition {source['edition']}.",
        "-- PREREQUISITE: QG ADIF's `adif` schema is loaded first (the foreign keys point into it),",
        f"-- with ADIF {adif}.",
        "-- " + "=" * 77,
        "BEGIN;",
        f"DROP SCHEMA IF EXISTS {s} CASCADE;",
        f"CREATE SCHEMA {s};",
        "",
        "-- Where every fact here came from: SOURCE.json (owner, document URL, SHA-256).",
        f"CREATE TABLE {s}.source (",
        "    singleton boolean PRIMARY KEY DEFAULT TRUE CHECK (singleton),",
        "    document  jsonb NOT NULL",
        ");",
        f"INSERT INTO {s}.source (document) VALUES ({sql_str(json.dumps(source, ensure_ascii=False))}::jsonb);",
        "",
        f"CREATE TABLE {s}.code (",
        "    list               text    NOT NULL,",
        "    seq                integer NOT NULL,",
        "    code               text    NOT NULL,",
        "    name               text,",
        "    valid_from         date,",
        "    valid_to           date,",
        "    replaced_by        text,",
        "    attributes         jsonb,",
        "    source             text    NOT NULL,",
        "    transcription_note text,",
        "    PRIMARY KEY (list, seq)",
        ");",
        f"CREATE INDEX code_code ON {s}.code (code);",
        "",
        "-- What each code covers, in ADIF's own codes. pas_key is ADIF's record key for the",
        "-- subdivision (code.entity, e.g. 'QC.1'): ADIF's subdivision table has no other unique key.",
        f"CREATE TABLE {s}.cover (",
        "    list         text    NOT NULL,",
        "    seq          integer NOT NULL,",
        "    n            integer NOT NULL,",
        f"    adif_version text    NOT NULL DEFAULT {sql_str(adif)},",
        "    dxcc         integer,",
        "    pas          text,",
        "    pas_key      text GENERATED ALWAYS AS (pas || '.' || dxcc::text) STORED,",
        "    prefix       text,",
        "    boundary     text,",
        "    PRIMARY KEY (list, seq, n),",
        f"    FOREIGN KEY (list, seq) REFERENCES {s}.code (list, seq),",
        "    FOREIGN KEY (adif_version, dxcc) REFERENCES adif.dxcc_entity_code (adif_version, entity_code),",
        "    FOREIGN KEY (adif_version, pas_key) REFERENCES adif.primary_administrative_subdivision (adif_version, record_key)",
        ");",
        f"CREATE INDEX cover_entity ON {s}.cover (dxcc, pas);",
        "",
    ]
    for d in facts.values():
        for seq, r in enumerate(d["records"], 1):
            out.append(
                f"INSERT INTO {s}.code VALUES ({sql_str(d['list'])}, {seq}, {sql_str(r['code'])}, "
                f"{sql_str(r['name'])}, {sql_str(r['valid_from'])}, {sql_str(r['valid_to'])}, "
                f"{sql_str(r['replaced_by'])}, "
                f"{sql_str(json.dumps(r['attributes'], ensure_ascii=False)) + '::jsonb' if r.get('attributes') else 'NULL'}, "
                f"{sql_str(r['source'])}, {sql_str(r.get('transcription_note'))});"
            )
            for n, c in enumerate(r["covers"], 1):
                out.append(
                    f"INSERT INTO {s}.cover (list, seq, n, dxcc, pas, prefix, boundary) VALUES "
                    f"({sql_str(d['list'])}, {seq}, {n}, {sql_str(c['dxcc'])}, {sql_str(c['pas'])}, "
                    f"{sql_str(c['prefix'])}, {sql_str(c['boundary'])});"
                )
    out += [
        "",
        "DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ionis_ro') THEN",
        f"  GRANT USAGE ON SCHEMA {s} TO ionis_ro;",
        f"  GRANT SELECT ON ALL TABLES IN SCHEMA {s} TO ionis_ro;",
        "END IF; END $$;",
        "COMMIT;",
        "",
    ]
    return "\n".join(out)


def main(check_only: bool) -> None:
    source = json.loads((DATA / "SOURCE.json").read_text(encoding="utf-8"))
    check_published(source)
    package_build.read_published(PUBLISHED, DATA, source, write=not check_only)
    facts = check_facts(source)
    outputs = {DATA / "derived" / n: dump(v) for n, v in package_build.derived(source, facts).items()}
    outputs[DATA / "load.sql"] = load_sql(source, facts)
    stale = [p for p, text in outputs.items() if not p.exists() or p.read_text(encoding="utf-8") != text]
    if check_only:
        if stale:
            sys.exit("stale, run scripts/build.py: " + ", ".join(str(p.relative_to(ROOT)) for p in stale))
        print("ok: published, facts, derived and load.sql are current")
        return
    for p in stale:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(outputs[p], encoding="utf-8")
    print(f"ok: {len(stale)} file(s) written")


if __name__ == "__main__":
    main("--check" in sys.argv[1:])
